### ISSUE TITLE
Compatibility with non-unicode

### ISSUE THREAD

**Issue by plater777** [CheckPoint-APIs-Team/ExportObjects#1]
Hi all, I dunno if you are tracking the issues here but I want to let you know that the get_objects.py script doesn't work if you have objects in the Check Point database using non unicode characters: I'm not US based so some objects may have spanish accents or such.

The workaround I found to solve the issue is to add the following two lines after the line 10 (>>> import sys):

>>> reload(sys)
>>> sys.setdefaultencoding('utf-8')

Obviously this force the encoding to UTF-8 to accept the non-unicode characters but it's not a "perfect" solution.

**Comment by chkp-rdecker** [comment]
Thank you for pointing us to this issue.
Will be fixed ASAP.

**Comment by chkp-amiads** [comment]
@plater777 , thanks for you feedback, issue was fixed.
