### ISSUE TITLE
Login failed: APIResponse received a response which is not a valid JSON.

### ISSUE THREAD

**Issue by hundfred** [CheckPoint-APIs-Team/ExportObjects#2]
what is missing?
how to debug?

 python export_hosts.py -m <IP> -u <username>
Trying to get login credentials...
Trying to login via `mgmt_cli login -r true.
Trying to get username and password.
Enter password:
Got the following login credentials:
    Username: username
    Password: ***************
    Session ID: None
Login failed: APIResponse received a response which is not a valid JSON.

**Comment by chkp-amiads** [comment]
Please do the following:
1. reproduce issue
2. on the Mgmt machine execute 'api status -s' 
3. send .tgz file (debug logs) to amiads@checkpoint.com
